# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20181215_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
